### ISSUE TITLE
don't run

### ISSUE THREAD

**Issue by kang2k10** [jethornton/7i97#1]
error:
```
Traceback (most recent call last):
  File "/usr/bin/7i97", line 214, in <module>
    main()
  File "/usr/bin/7i97", line 210, in main
    ex = MainWindow()
  File "/usr/bin/7i97", line 77, in __init__
    self.setupConnections()
  File "/usr/bin/7i97", line 94, in setupConnections
    self.actionCheckUpdates.triggered.connect(partial(updates.checkUpdates, self))
AttributeError: 'MainWindow' object has no attribute 'actionCheckUpdates'
```

how fix this ?
Debian GNU/Linux 10 (buster)
LinuxCNC 2.8.2

**Comment by jethornton** [comment]
I'll fix that in the morning, thanks for the report. Just so you know the [Mesa Configuration Tool](https://gnipsel.com/mesa/mesact/index.html) will also do the 7i97 with perhaps more features.
JT

**Comment by jethornton** [comment]
Also make sure you have the latest deb
